### ISSUE TITLE
Uncaught Error: Cannot find module 'sort-sass'

### ISSUE THREAD

**Issue by znoy** [miraks/atom-sort-sass#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.209.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [sort-sass](https://github.com/miraks/atom-sort-sass) package, v0.1.0
### Stack Trace

Uncaught Error: Cannot find module 'sort-sass'

```
At module.js:330

Error: Cannot find module 'sort-sass'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (C:\Users\Znoy\AppData\Local\atom\app-0.209.0\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Znoy\.atom\packages\sort-sass\lib\sort-sass.coffee:2:12)
  at Object.<anonymous> (C:\Users\Znoy\.atom\packages\sort-sass\lib\sort-sass.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\Znoy\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\Znoy\AppData\Local\atom\app-0.209.0\resources\app.asar\src\package.js:709:34)
  at Package.module.exports.Package.activateConfig (C:\Users\Znoy\AppData\Local\atom\app-0.209.0\resources\app.asar\src\package.js:257:12)
  at PackageDetailView.module.exports.PackageDetailView.activate (C:\Users\Znoy\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:163:26)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (C:\Users\Znoy\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:201:12)
  at C:\Users\Znoy\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:235:24
  at C:\Users\Znoy\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\emissary\lib\emitter.js:155:30
  at Array.forEach (native)
  at PackageManager.module.exports.Emitter.emitSlow (C:\Users\Znoy\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\emissary\lib\emitter.js:154:47)
  at PackageManager.module.exports.Emitter.emit (C:\Users\Znoy\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\emissary\lib\emitter.js:107:30)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (C:\Users\Znoy\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:546:19)
  at C:\Users\Znoy\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:369:26
  at exit (C:\Users\Znoy\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:53:16)
  at triggerExitCallback (C:\Users\Znoy\AppData\Local\atom\app-0.209.0\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\Znoy\AppData\Local\atom\app-0.209.0\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```
### Commands

```
     -3:27.4.0 pane:reopen-closed-item (atom-text-editor.editor.is-focused)
     -3:16.3.0 application:add-project-folder (atom-text-editor.editor.is-focused)
     -2:41.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "disabledPackages": [
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-perl",
      "language-objective-c",
      "language-mustache",
      "language-make",
      "language-java",
      "language-go",
      "language-csharp",
      "language-clojure",
      "language-c"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
color-picker, v2.0.4
seti-syntax, v0.4.0
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by miraks** [comment]
Should be fixed now
